language: java
sudo: true
branches:
  only:
  - master
jdk:
- openjdk8
matrix:
  include:
    - language:node_js
      node_js: 10
      before_script:
        - cd src/main/react-front-end
        - npm install
      script:
        - npm run build
before_install:
- echo "before_install"

deploy:
- provider: script
  skip_cleanup: true
  script: cd target && ls
  
script: "./mvnw clean install"
notifications:
  email:
    - kprabhak@buffalo.edu