language: java
sudo: true
branches:
  only:
  - master
jdk:
- openjdk8
jobs:
  include:  
    - language: node_js
      node_js: 10
      before_script:
      - cd src/main/react-front-end
      - npm install
      script:
      - node -e "console.log('Hi from NodeJS!')"
      - npm run build
      after_script:
      - cd build && ls 
      deploy:
      - provider: script
        skip_cleanup: true
        script: echo "deploy of ui"
      
    - language: java
      jdk: openjdk8
      script:
      - mvn clean install
      after_script:
      - cd target && ls 
      deploy:
      - provider: script
        skip_cleanup: true
        script: echo "deploy of service"

before_install:
- echo "before_install"


notifications:
  email:
    - kprabhak@buffalo.edu