language: java
sudo: true
branches:
  only:
  - master
jdk:
- openjdk8
jobs:
  include:
    - language: node_js
      node_js: 10
      before_script:
      - cd src/main/react-front-end
      - npm install
      script:
      - node -e "console.log('Hi from NodeJS!')"
      - npm run build
      after_script:
      - cd build && ls
      
    - language: java
      jdk: openjdk8
      before_script:
      - echo "starting java build"
      - chmod +x mvnw
      - pwd
      script:
      - ./mvnw clean install
      after_script:
      - cd target && ls 

before_install:
- echo "before_install"


notifications:
  email:
    - kprabhak@buffalo.edu