language: java
sudo: true
branches:
  only:
  - master
jdk:
- openjdk8
jobs:
  include:
    - language: node_js
      node_js: 10
      before_script:
      - cd src/main/react-front-end
      - npm install
      script:
      - node -e "console.log('Hi from NodeJS!')"
      - npm run build
    - language: java
      jdk: openjdk8
      before_script:
      - cd ../../../
      - node -e "console.log('Started java build')"
      - pwd
      script:
      - ./mvnw clean install

before_install:
- echo "before_install"


notifications:
  email:
    - kprabhak@buffalo.edu