language: java
sudo: true
branches:
  only:
  - master
jdk:
- openjdk8
jobs:
  include:
    - stage: front-end
    - language: node_js
      node_js: 10
      before_script:
      - cd src/main/react-front-end
      - npm install
      script:
      - node -e "console.log('Hi from NodeJS!')"
      - npm run build
      after_script:
      - cd build && ls 
      deploy:
      - provider: script
        skip_cleanup: true
        script: echo "deploy of ui"
      
    - stage: back-end
    - language: java
      jdk: openjdk8
      install: true
      script:
      - mvn install:install-file -Dfile=./lib/globus-api-1.1-SNAPSHOT.jar -DgroupId=org.onedatashare.module  -DartifactId=globus-api -Dversion=1.1-SNAPSHOT -Dpackaging=jar && mvn package
      after_script:
      - cd target && ls 
      deploy:
      - provider: script
        skip_cleanup: true
        script: echo "deploy of service"

before_install:
- echo "before_install"
- chmod +x mvnw

notifications:
  email:
    - kprabhak@buffalo.edu